### ISSUE TITLE
Lovely Theme! Two highlights to add

### ISSUE THREAD

**Issue by dxps** [deeppines/pines-visual-studio-code#13]
Hi @deeppines !

I simply love this theme, switched to it from Material Theme and used since then.
So, first of all, thank you for making and sharing it! :clap: 

Two things I would consider needs some highlight:
1. The bottom views titles/tabs (problems, output, debug console, and terminal) should illustrate a little bit which of them is open. Currently, all four titles looks the same. A little bit of either text color difference would be enough. Not necessarily that strong orange underline that exists on the active tab of the editor.
   
   
  ![image](https://user-images.githubusercontent.com/14140226/51735274-a5779300-208f-11e9-89b9-60550035d69d.png)

2. Selected text on the Settings field is not highlighted at all.
  
![image](https://user-images.githubusercontent.com/14140226/51737197-ad860180-2094-11e9-9acc-7076cee53910.png)

Thanks

**Comment by deeppines** [comment]
Thanks for your feedback!

I'm fixed titles in Panel tabs and highlighted text in input, but strong orange underline is not in my theme. I think you need check your `workbench.colorCustomizations` settings.

**Comment by dxps** [comment]
You're right. The orangle underline is a custom setting:

Thanks for the quick response and update. The result is perfect! 👏 

Selected text is now correctly displayed: 👍 
![image](https://user-images.githubusercontent.com/14140226/51800397-ce865800-2236-11e9-8cdf-f0ba7655843e.png)


Active console is highlighted enough to be distinct, but not too much to distract you:  👍 
![image](https://user-images.githubusercontent.com/14140226/51800364-85360880-2236-11e9-80b8-dd0f0e913e24.png)
